targets := target1 target3 target2


all: $(targets)
	echo "finished"

target1:
	echo "this is target1"
	touch target1
target2:
	echo "this is target2"
	touch target2
target3:
	echo "this is target3"
	touch target3
clean:
	rm -f $(targets)
